// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Character struct {
	ID    int64
	Name  string
	Type  string
	Scale float64
	Image string
}

type Game struct {
	ID         int64
	Grid       string
	Background string
	TileSize   int64
	HideTiles  bool
}

type GameCharacter struct {
	GameID      int64
	CharacterID int64
	X           int64
	Y           int64
}
