// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (name, type, scale, image) VALUES (?, ?, ?, ?) RETURNING id, name, type, scale, image
`

type CreateCharacterParams struct {
	Name  string
	Type  string
	Scale float64
	Image string
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, createCharacter,
		arg.Name,
		arg.Type,
		arg.Scale,
		arg.Image,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Scale,
		&i.Image,
	)
	return i, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (grid, background, tile_size) VALUES (?, ?, ?) RETURNING id, grid, background, tile_size, hide_tiles
`

type CreateGameParams struct {
	Grid       string
	Background string
	TileSize   int64
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame, arg.Grid, arg.Background, arg.TileSize)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Grid,
		&i.Background,
		&i.TileSize,
		&i.HideTiles,
	)
	return i, err
}

const createGameCharacter = `-- name: CreateGameCharacter :one
INSERT INTO game_characters (game_id, character_id, x, y) VALUES (?, ?, ?, ?) RETURNING game_id, character_id, x, y
`

type CreateGameCharacterParams struct {
	GameID      int64
	CharacterID int64
	X           int64
	Y           int64
}

func (q *Queries) CreateGameCharacter(ctx context.Context, arg CreateGameCharacterParams) (GameCharacter, error) {
	row := q.db.QueryRowContext(ctx, createGameCharacter,
		arg.GameID,
		arg.CharacterID,
		arg.X,
		arg.Y,
	)
	var i GameCharacter
	err := row.Scan(
		&i.GameID,
		&i.CharacterID,
		&i.X,
		&i.Y,
	)
	return i, err
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, grid, background, tile_size, hide_tiles FROM games WHERE id = ?
`

func (q *Queries) GetGameByID(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Grid,
		&i.Background,
		&i.TileSize,
		&i.HideTiles,
	)
	return i, err
}

const getGameCharacterByID = `-- name: GetGameCharacterByID :one
SELECT c.id, c.name, c.type, c.scale, c.image, gc.x, gc.y FROM characters c
JOIN game_characters gc ON c.id = gc.character_id
WHERE gc.game_id = ? AND c.id = ?
`

type GetGameCharacterByIDParams struct {
	GameID int64
	ID     int64
}

type GetGameCharacterByIDRow struct {
	ID    int64
	Name  string
	Type  string
	Scale float64
	Image string
	X     int64
	Y     int64
}

func (q *Queries) GetGameCharacterByID(ctx context.Context, arg GetGameCharacterByIDParams) (GetGameCharacterByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getGameCharacterByID, arg.GameID, arg.ID)
	var i GetGameCharacterByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Scale,
		&i.Image,
		&i.X,
		&i.Y,
	)
	return i, err
}

const getGameCharacters = `-- name: GetGameCharacters :many
SELECT c.id, c.name, c.type, c.scale, c.image, gc.x, gc.y FROM characters c
JOIN game_characters gc ON c.id = gc.character_id
WHERE gc.game_id = ?
`

type GetGameCharactersRow struct {
	ID    int64
	Name  string
	Type  string
	Scale float64
	Image string
	X     int64
	Y     int64
}

func (q *Queries) GetGameCharacters(ctx context.Context, gameID int64) ([]GetGameCharactersRow, error) {
	rows, err := q.db.QueryContext(ctx, getGameCharacters, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameCharactersRow
	for rows.Next() {
		var i GetGameCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Scale,
			&i.Image,
			&i.X,
			&i.Y,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hideGameTiles = `-- name: HideGameTiles :exec
UPDATE games SET hide_tiles = ? WHERE id = ?
`

type HideGameTilesParams struct {
	HideTiles bool
	ID        int64
}

func (q *Queries) HideGameTiles(ctx context.Context, arg HideGameTilesParams) error {
	_, err := q.db.ExecContext(ctx, hideGameTiles, arg.HideTiles, arg.ID)
	return err
}

const updateCharacterPosition = `-- name: UpdateCharacterPosition :exec
UPDATE game_characters SET x = ?, y = ? WHERE game_id = ? AND character_id = ?
`

type UpdateCharacterPositionParams struct {
	X           int64
	Y           int64
	GameID      int64
	CharacterID int64
}

func (q *Queries) UpdateCharacterPosition(ctx context.Context, arg UpdateCharacterPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateCharacterPosition,
		arg.X,
		arg.Y,
		arg.GameID,
		arg.CharacterID,
	)
	return err
}

const updateGameGrid = `-- name: UpdateGameGrid :exec
UPDATE games SET grid = ? WHERE id = ?
`

type UpdateGameGridParams struct {
	Grid string
	ID   int64
}

func (q *Queries) UpdateGameGrid(ctx context.Context, arg UpdateGameGridParams) error {
	_, err := q.db.ExecContext(ctx, updateGameGrid, arg.Grid, arg.ID)
	return err
}
